name: CI

on:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master
    - develop

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Node 16
      uses: actions/setup-node@v1
      with:
        node-version: '16'
        cache: 'yarn'
    - name: yarn install & test
      run: |
        yarn install
        yarn test --ci
